# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
# Added at 2017-10-30 16:13:34 +0300 by next\gektor:
gem 'rubocop', '~> 0.51.0'
