# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'

gem 'sinatra-contrib', '~> 2.0'

gem 'minitest', '~> 5.10'

gem 'capybara', '~> 2.16'

gem 'puma', '~> 3.11'

gem 'rake', '~> 12.3'

gem 'rubocop', '~> 0.52.1'

gem "simplecov", "~> 0.15.1"

gem "mocha", "~> 1.3"