require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'app/views'
  t.libs << 'app'
  t.libs << 'app/source'
  t.test_files = FileList['test/**/*_test.rb']
end

task default: :test
